//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDealership.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Special
    {
        public int SpecialID { get; set; }
        public string SpecialName { get; set; }
        public string SpecialDescription { get; set; }
    }
}
